apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
spec:
  rules:
  - host: localhost
  - http:
      paths:
      - path: /news_service
        backend:
          serviceName: news_service
          port:
            number: 8080
      - path: /similarity_service
        backend:
          serviceName: similarity_service
          port:
            number: 5000
    